/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Datos.Persona;
import Logica.fPersona;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author DELLPHOTO
 */
public class frmRegistroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form frmInicioSesion
     */
    public frmRegistroUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtyatengocuenta = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        txtcontrasenia = new javax.swing.JPasswordField();
        btnregistrarse = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        txtapellidop = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        txtapellidom = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        txtnombre = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblSalir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(97, 212, 195));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 210, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));

        jLabel1.setFont(new java.awt.Font("Fredoka One", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("UNIBNB");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 180, 49));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 630));

        jPanel3.setBackground(new java.awt.Color(34, 44, 76));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(97, 212, 195));
        jLabel4.setText("Registro");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jLabel11.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("CONTRASEÑA");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, -1));

        txtyatengocuenta.setBackground(new java.awt.Color(36, 47, 65));
        txtyatengocuenta.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtyatengocuenta.setForeground(new java.awt.Color(97, 212, 195));
        txtyatengocuenta.setText("Ya tengo cuenta");
        txtyatengocuenta.setBorder(null);
        txtyatengocuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtyatengocuenta.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtyatengocuenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtyatengocuentaFocusGained(evt);
            }
        });
        txtyatengocuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtyatengocuentaMouseClicked(evt);
            }
        });
        txtyatengocuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtyatengocuentaActionPerformed(evt);
            }
        });
        jPanel3.add(txtyatengocuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, 110, -1));

        jSeparator6.setForeground(new java.awt.Color(97, 212, 195));
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, 120, 20));

        jLabel12.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("NOMBRE");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 310, 20));

        txtcontrasenia.setBackground(new java.awt.Color(36, 47, 65));
        txtcontrasenia.setForeground(new java.awt.Color(255, 255, 255));
        txtcontrasenia.setText("jPasswordField1");
        txtcontrasenia.setBorder(null);
        txtcontrasenia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcontraseniaFocusGained(evt);
            }
        });
        jPanel3.add(txtcontrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, -1, -1));

        btnregistrarse.setBackground(new java.awt.Color(97, 212, 195));
        btnregistrarse.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnregistrarse.setForeground(new java.awt.Color(255, 255, 255));
        btnregistrarse.setText("Registrarse");
        btnregistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnregistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarseActionPerformed(evt);
            }
        });
        jPanel3.add(btnregistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, 110, 40));

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 310, 20));

        jLabel13.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("USUARIO");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        txtusuario.setBackground(new java.awt.Color(36, 47, 65));
        txtusuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtusuario.setForeground(new java.awt.Color(255, 255, 255));
        txtusuario.setText("Ingresa tu usuario");
        txtusuario.setBorder(null);
        txtusuario.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtusuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtusuarioFocusGained(evt);
            }
        });
        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });
        jPanel3.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 310, 20));

        jLabel14.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("PRIMER APELLIDO");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        txtapellidop.setBackground(new java.awt.Color(36, 47, 65));
        txtapellidop.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtapellidop.setForeground(new java.awt.Color(255, 255, 255));
        txtapellidop.setText("Ingresa tu primer apellido");
        txtapellidop.setBorder(null);
        txtapellidop.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtapellidop.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtapellidopFocusGained(evt);
            }
        });
        txtapellidop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapellidopActionPerformed(evt);
            }
        });
        jPanel3.add(txtapellidop, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jSeparator10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 310, 20));

        txtapellidom.setBackground(new java.awt.Color(36, 47, 65));
        txtapellidom.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtapellidom.setForeground(new java.awt.Color(255, 255, 255));
        txtapellidom.setText("Ingresa tu segundo apellido");
        txtapellidom.setBorder(null);
        txtapellidom.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtapellidom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtapellidomFocusGained(evt);
            }
        });
        txtapellidom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapellidomActionPerformed(evt);
            }
        });
        jPanel3.add(txtapellidom, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jSeparator11.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 310, 20));

        jLabel15.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("SEGUNDO APELLIDO");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel16.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("CORREO ELECTRÓNICO");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        txtcorreo.setBackground(new java.awt.Color(36, 47, 65));
        txtcorreo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtcorreo.setForeground(new java.awt.Color(255, 255, 255));
        txtcorreo.setText("Ingresa tu correo electrónico");
        txtcorreo.setBorder(null);
        txtcorreo.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtcorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcorreoFocusGained(evt);
            }
        });
        txtcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcorreoActionPerformed(evt);
            }
        });
        jPanel3.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        jSeparator12.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 310, 20));

        txtnombre.setBackground(new java.awt.Color(36, 47, 65));
        txtnombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtnombre.setForeground(new java.awt.Color(255, 255, 255));
        txtnombre.setText("Ingresa tu primer apellido");
        txtnombre.setBorder(null);
        txtnombre.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtnombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnombreFocusGained(evt);
            }
        });
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        jPanel3.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel17.setBackground(new java.awt.Color(36, 47, 65));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo 2.png"))); // NOI18N
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 250, 490));

        jLabel18.setBackground(new java.awt.Color(36, 47, 65));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo 2.png"))); // NOI18N
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 300, 490));

        lblSalir.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lblSalir.setForeground(new java.awt.Color(255, 255, 255));
        lblSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalir.setText("X");
        lblSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSalirMouseExited(evt);
            }
        });
        jPanel3.add(lblSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 40, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 480, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtyatengocuentaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtyatengocuentaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtyatengocuentaFocusGained

    private void txtyatengocuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtyatengocuentaActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new frmInicioSesion().setVisible(true);
    }//GEN-LAST:event_txtyatengocuentaActionPerformed

    private void txtcontraseniaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcontraseniaFocusGained
        // TODO add your handling code here:
        txtcontrasenia.setText("");
    }//GEN-LAST:event_txtcontraseniaFocusGained

    private void btnregistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarseActionPerformed
        // TODO add your handling code here:
        if (txtnombre.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar un Nombre");
            txtnombre.requestFocus();
            return;
        }
        if (txtapellidop.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar tu Primer Apellido");
            txtapellidop.requestFocus();
            return;
        }
        if (txtapellidom.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar tu Segundo Apellido");
            txtapellidom.requestFocus();
            return;
        }
        if (txtcorreo.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar tu correo electrónico");
            txtcorreo.requestFocus();
            return;
        }
        if (txtusuario.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar tu usuario");
            txtusuario.requestFocus();
            return;
        }
        if (txtcontrasenia.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar tu contraseña");
            txtcontrasenia.requestFocus();
            return;
        }
        
        Persona dts = new Persona();
        fPersona func = new fPersona();
        frmMenuPrincipal menu = new frmMenuPrincipal();
        
        dts.setNombre(txtnombre.getText());
        dts.setApaterno(txtapellidop.getText());
        dts.setAmaterno(txtapellidom.getText());
        dts.setEmail(txtcorreo.getText());
        dts.setUsuario(txtusuario.getText());
        dts.setPassword(txtcontrasenia.getText());
        
        if (func.insertar(dts)) {
            menu.usuario = dts.getUsuario();
            JOptionPane.showMessageDialog(rootPane, "El usuario "+ menu.usuario +" fue registrado satisfactoriamente");
            setVisible(false);
            new frmInicioSesion().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Error al registrar al usuario");
        }
    }//GEN-LAST:event_btnregistrarseActionPerformed

    private void txtusuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusuarioFocusGained
        // TODO add your handling code here:
        txtusuario.setText("");
    }//GEN-LAST:event_txtusuarioFocusGained

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuarioActionPerformed

    private void txtapellidopFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtapellidopFocusGained
        // TODO add your handling code here:
        txtapellidop.setText("");
    }//GEN-LAST:event_txtapellidopFocusGained

    private void txtapellidopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapellidopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidopActionPerformed

    private void txtapellidomFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtapellidomFocusGained
        // TODO add your handling code here:
        txtapellidom.setText("");
    }//GEN-LAST:event_txtapellidomFocusGained

    private void txtapellidomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapellidomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidomActionPerformed

    private void txtcorreoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcorreoFocusGained
        // TODO add your handling code here:
        txtcorreo.setText("");
    }//GEN-LAST:event_txtcorreoFocusGained

    private void txtcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorreoActionPerformed

    private void txtnombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnombreFocusGained
        // TODO add your handling code here:
        txtnombre.setText("");
    }//GEN-LAST:event_txtnombreFocusGained

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtyatengocuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtyatengocuentaMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new frmInicioSesion().setVisible(true);
    }//GEN-LAST:event_txtyatengocuentaMouseClicked

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        // TODO add your handling code here:
        int confirmacion = JOptionPane.showConfirmDialog(rootPane, "¿Deseas Salir De La Aplicación?", "Confirmar", 2);
        if (confirmacion == 0) 
            System.exit(0);
    }//GEN-LAST:event_lblSalirMouseClicked

    private void lblSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseEntered
        // TODO add your handling code here:
        lblSalir.setForeground(Color.red);
    }//GEN-LAST:event_lblSalirMouseEntered

    private void lblSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseExited
        // TODO add your handling code here:
        lblSalir.setForeground(Color.white);
    }//GEN-LAST:event_lblSalirMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegistroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnregistrarse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblSalir;
    public static javax.swing.JTextField txtapellidom;
    public static javax.swing.JTextField txtapellidop;
    private javax.swing.JPasswordField txtcontrasenia;
    public static javax.swing.JTextField txtcorreo;
    public static javax.swing.JTextField txtnombre;
    public static javax.swing.JTextField txtusuario;
    public static javax.swing.JTextField txtyatengocuenta;
    // End of variables declaration//GEN-END:variables
}
