/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;
import Logica.fHabitacion;
import Datos.Reserva;
import Logica.fReserva;
import java.awt.Color;
import java.util.Calendar;
import java.sql.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author ANDERSON
 */
public class frmReservaHabitacion extends javax.swing.JFrame {

    frmBusqueda busqueda = new frmBusqueda();
    frmMenuPrincipal menu = new frmMenuPrincipal();
    /**
     * Creates new form frmHabitacion
     */
    public frmReservaHabitacion() {
        initComponents();
        txtidhabitacion.setText(Integer.toString(busqueda.idHabitacion));
        txtidhabitacion.setEnabled(false);
        txtcosto_reserva.setEnabled(false);
    }
    public double costoR (){
        Calendar inicio, fin;
        fHabitacion func = new fHabitacion();
        int dias;
        long finMS, inicioMS;
        double costDia, costoReserva;
        
        inicio = dcfecha_ingreso.getCalendar();
        fin = dcfecha_salida.getCalendar();
        
        inicio.set(Calendar.HOUR,0);
        inicio.set(Calendar.HOUR_OF_DAY,0);
        inicio.set(Calendar.MINUTE,0);
        inicio.set(Calendar.SECOND,0);
        
        fin.set(Calendar.HOUR,0);
        fin.set(Calendar.HOUR_OF_DAY,0);
        fin.set(Calendar.MINUTE,0);
        fin.set(Calendar.SECOND,0);
        
        inicioMS = inicio.getTimeInMillis();
        finMS = fin.getTimeInMillis();
        
        dias = (int)(((Math.abs(finMS-inicioMS))/(1000*60*60*24))+1);
        costDia = func.costoDia(busqueda.idHabitacion);
        costoReserva = costDia*dias;
        txtcosto_reserva.setText("$"+ Double.toString(costoReserva));
        return costoReserva;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        dcfecha_salida = new com.toedter.calendar.JDateChooser();
        jSeparator6 = new javax.swing.JSeparator();
        txtidhabitacion = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtcosto_reserva = new javax.swing.JTextPane();
        dcfecha_ingreso = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnreservar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblSalir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(97, 212, 195));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dcfecha_salida.setBackground(new java.awt.Color(79, 172, 158));
        jPanel2.add(dcfecha_salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 180, -1));

        jSeparator6.setForeground(new java.awt.Color(97, 212, 195));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 140, 20));

        txtidhabitacion.setBackground(new java.awt.Color(79, 172, 158));
        txtidhabitacion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtidhabitacion.setForeground(new java.awt.Color(255, 255, 255));
        txtidhabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidhabitacionActionPerformed(evt);
            }
        });
        jPanel2.add(txtidhabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 70, 30));

        jLabel16.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Fecha Salida:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 130, 30));

        txtcosto_reserva.setBackground(new java.awt.Color(204, 255, 255));
        txtcosto_reserva.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtcosto_reserva.setForeground(new java.awt.Color(34, 44, 76));
        txtcosto_reserva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcosto_reservaKeyTyped(evt);
            }
        });
        jScrollPane4.setViewportView(txtcosto_reserva);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 200, -1));

        dcfecha_ingreso.setBackground(new java.awt.Color(79, 172, 158));
        jPanel2.add(dcfecha_ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 180, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("Calcular Costo");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 130, 30));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha Ingreso:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 130, 30));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Id:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, 30));

        jLabel3.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Reserva Habitación");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 320, 49));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 230, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.png"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 630));

        jPanel3.setBackground(new java.awt.Color(36, 47, 65));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(36, 47, 65));
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 110, 20));

        jPanel4.setBackground(new java.awt.Color(34, 44, 76));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        btnreservar.setBackground(new java.awt.Color(97, 212, 195));
        btnreservar.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnreservar.setText("Reservar");
        btnreservar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnreservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreservarActionPerformed(evt);
            }
        });
        jPanel4.add(btnreservar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 100, 50));

        btncancelar.setBackground(new java.awt.Color(97, 212, 195));
        btncancelar.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        jPanel4.add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, 100, 50));

        jLabel1.setFont(new java.awt.Font("Fredoka One", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("UNIBNB");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 180, 49));

        jLabel11.setBackground(new java.awt.Color(36, 47, 65));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo 2.png"))); // NOI18N
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 200, 490));

        jLabel13.setBackground(new java.awt.Color(36, 47, 65));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo 2.png"))); // NOI18N
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, 490));

        lblSalir.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lblSalir.setForeground(new java.awt.Color(255, 255, 255));
        lblSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalir.setText("X");
        lblSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSalirMouseExited(evt);
            }
        });
        jPanel4.add(lblSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 40, 40));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 630));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 480, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtidhabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidhabitacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidhabitacionActionPerformed

    private void btnreservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreservarActionPerformed
        // TODO add your handling code here:
        
        Reserva dts = new Reserva();
        fReserva func = new fReserva();
        
        Calendar inicio, fin;
        int d,m,a;

        dts.setIdHabitacion(busqueda.idHabitacion);
        dts.setCliente(menu.usuario);
        
        inicio = dcfecha_ingreso.getCalendar();
        d = inicio.get(Calendar.DAY_OF_MONTH);
        m = inicio.get(Calendar.MONTH);
        a = inicio.get(Calendar.YEAR)-1900;
        dts.setFecha_ingreso(new Date(a,m,d));
        
        fin = dcfecha_salida.getCalendar();
        d = fin.get(Calendar.DAY_OF_MONTH);
        m = fin.get(Calendar.MONTH);
        a = fin.get(Calendar.YEAR)-1900;
        dts.setFecha_salida(new Date(a,m,d));
        
        double c = costoR();
        dts.setCosto_reserva(c);
        
        String estado = "Alquilada";
        dts.setEstado(estado);
        
        if (func.insertar(dts)) {
            JOptionPane.showMessageDialog(rootPane, "La Reserva Fue Registrada Satisfactoriamente");

        } else {
            JOptionPane.showMessageDialog(rootPane, "Error Al Hacer La Reserva De La Habitación");
        }
    }//GEN-LAST:event_btnreservarActionPerformed

    private void txtcosto_reservaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcosto_reservaKeyTyped
        // TODO add your handling code here: 
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar un valor válido");
        }
    }//GEN-LAST:event_txtcosto_reservaKeyTyped

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        frmMenuPrincipal menu = new frmMenuPrincipal();
        menu.lblusuario.setText(menu.usuario);
        setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_btncancelarActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        costoR();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        // TODO add your handling code here:
        int confirmacion = JOptionPane.showConfirmDialog(rootPane, "¿Deseas Salir De La Aplicación?", "Confirmar", 2);
        if (confirmacion == 0) 
            System.exit(0);
    }//GEN-LAST:event_lblSalirMouseClicked

    private void lblSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseEntered
        // TODO add your handling code here:
        lblSalir.setForeground(Color.red);
    }//GEN-LAST:event_lblSalirMouseEntered

    private void lblSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseExited
        // TODO add your handling code here:
        lblSalir.setForeground(Color.white);
    }//GEN-LAST:event_lblSalirMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReservaHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReservaHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReservaHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReservaHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReservaHabitacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnreservar;
    private com.toedter.calendar.JDateChooser dcfecha_ingreso;
    private com.toedter.calendar.JDateChooser dcfecha_salida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblSalir;
    private javax.swing.JTextPane txtcosto_reserva;
    private javax.swing.JTextField txtidhabitacion;
    // End of variables declaration//GEN-END:variables
}
