-- MySQL Script generated by MySQL Workbench
-- Fri May 27 12:16:54 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema baseUnibnb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema baseUnibnb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `baseUnibnb` DEFAULT CHARACTER SET utf8 ;
USE `baseUnibnb` ;

-- -----------------------------------------------------
-- Table `baseUnibnb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseUnibnb`.`Persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `apaterno` VARCHAR(20) NOT NULL,
  `amaterno` VARCHAR(20) NOT NULL,
  `email` VARCHAR(25) NOT NULL,
  `usuario` VARCHAR(25) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idPersona`),
  UNIQUE KEY `usuario_UNIQUE` (`usuario`) )
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `baseUnibnb`.`Habitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseUnibnb`.`Habitacion` (
  `idHabitacion` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(4) NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  `ubicacion` VARCHAR(25) NULL,
  `precio_diario` DECIMAL(7,2) NOT NULL,
  `estado` VARCHAR(15) NOT NULL,
  `tipo_habitacion` VARCHAR(45) NOT NULL,
  `arrendador` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idHabitacion`),
  KEY `fk_habitacion_arrendador_idx` (`arrendador` ),
  CONSTRAINT `fk_habitacion_arrendador`
    FOREIGN KEY (`arrendador`)
    REFERENCES `baseUnibnb`.`Persona` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baseUnibnb`.`Reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseUnibnb`.`Reserva` (
  `idReserva` INT NOT NULL AUTO_INCREMENT,
  `idHabitacion` INT NOT NULL,
  `cliente` VARCHAR(25) NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  `fecha_salida` DATE NOT NULL,
  `costo_reserva` DECIMAL(7,2) NOT NULL,
  `estado` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idReserva`),
  KEY `fk_reserva_habitacion_idx` (`idHabitacion` ),
  KEY `fk_reserva_cliente_idx` (`cliente`),
  CONSTRAINT `fk_reserva_habitacion`
    FOREIGN KEY (`idHabitacion`)
    REFERENCES `baseUnibnb`.`Habitacion` (`idHabitacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_cliente`
    FOREIGN KEY (`cliente`)
    REFERENCES `baseUnibnb`.`Persona` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baseUnibnb`.`Pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseUnibnb`.`Pago` (
  `idPago` INT NOT NULL AUTO_INCREMENT,
  `idReserva` INT NOT NULL,
  `tipo_comprobante` VARCHAR(20) NOT NULL,
  `num_comprobante` VARCHAR(20) NOT NULL,
  `igv` DECIMAL(4,2) NOT NULL,
  `total_pago` DECIMAL(7,2) NOT NULL,
  `fecha_emision` DATE NOT NULL,
  `fecha_pago` DATE NOT NULL,
  PRIMARY KEY (`idPago`),
  KEY `fk_pago_reserva_idx` (`idReserva`),
  CONSTRAINT `fk_pago_reserva`
    FOREIGN KEY (`idReserva`)
    REFERENCES `baseUnibnb`.`Reserva` (`idReserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
